import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
# -*- coding: utf-8 -*-
"""sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAsh8791yUOjp9Qpk6P5_kTYrMlsEWhe
"""

# Mount Google Drive for persistent storage
# from google.colab import drive
# drive.mount('/content/drive')

# ---------------------------------------------------------
# Hybrid Execution Pipeline: Auto-Detect Hardware System
# ---------------------------------------------------------
import subprocess, sys, os

def install_hybrid_dependencies():
    print("[Pre-Flight] Executing Hybrid Hardware Detection...")
    has_gpu = False
    try:
        subprocess.check_output(['nvidia-smi'])
        print("[System] NVIDIA GPU Detected. Validating CUDA Support...")
        has_gpu = True
    except Exception:
        print("[System] No GPU detected or missing nvidia-smi. Proceeding with CPU-Only Setup.")

    needs_install = None
    try:
        import torch
        if has_gpu and not torch.cuda.is_available():
            print("[Warning] PyTorch installed without CUDA! Flagging for GPU re-installation...")
            needs_install = "gpu"
    except ImportError:
        needs_install = "gpu" if has_gpu else "cpu"

    if needs_install:
        print(f"\n>>> [Auto-Installer] Starting Dependency Configuration for {'GPU (CUDA 12.1)' if needs_install == 'gpu' else 'CPU'}...")
        if needs_install == "gpu":
            subprocess.check_call([sys.executable, "-m", "pip", "install", "--force-reinstall", "torch", "torchvision", "torchaudio", "--index-url", "https://download.pytorch.org/whl/cu121"])
        else:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "torch", "torchvision", "torchaudio", "--index-url", "https://download.pytorch.org/whl/cpu"])

    # Validate Base Frameworks
    required = ['ultralytics', 'opencv-python>=4.5.0', 'tqdm', 'matplotlib', 'Flask']
    for pkg in required:
        pkg_name = pkg.split('>=')[0]
        try:
            __import__(pkg_name.lower() if pkg_name != 'opencv-python' else 'cv2')
        except ImportError:
            print(f">>> [Auto-Installer] Installing missing package: {pkg}...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", pkg])

install_hybrid_dependencies()
print("[Pre-Flight] Hybrid Dependencies Synthesized. Booting Engine...\n")

#Step 2: Analyze the Dataset (Traffic_data) Path

import os

# Path to your dataset
#dataset_path = '/content/drive/MyDrive/Traffic_data'
dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

# List the contents of the dataset directory
dataset_files = os.listdir(dataset_path)

# Display the contents
dataset_files

#Rename Folder names
import os

# Path to your dataset
dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

# Mapping of old names to new names
rename_map = {
    "cars": "Four Wheeler",
    "Large_Vehicle": "Large Vehicle",   # stays the same
    "KEKE_NAPEP": "Three Wheeler",
    "Two_Wheeler": "Two Wheeler"        # stays the same
}

# Rename folders
for old_name, new_name in rename_map.items():
    old_path = os.path.join(dataset_path, old_name)
    new_path = os.path.join(dataset_path, new_name)

    if os.path.exists(old_path) and old_name != new_name:
        os.rename(old_path, new_path)
        print(f"Renamed: {old_name} → {new_name}")
    else:
        print(f"No change: {old_name}")

# List final contents
print("\nFinal folder structure:")
print(os.listdir(dataset_path))

dataset_path

dataset_files

new_name

# List only folders (directories)
folders = [f for f in os.listdir(dataset_path) if os.path.isdir(os.path.join(dataset_path, f))]

print("Folders inside dataset:")
for folder in folders:
  print(folder)

#list the Two Wheeler folder and all its subfolders

target_folder = os.path.join(dataset_path, "Two Wheeler")

print(f"📂 {target_folder}")
subfolders = [f for f in os.listdir(target_folder) if os.path.isdir(os.path.join(target_folder, f))]
for sub in subfolders:
    print("   └──", sub)

# Paths
base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# Get sorted list of files
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
labels = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])

# Safety check: ensure same count
if len(images) != len(labels):
    print(f"⚠️ Warning: {len(images)} images and {len(labels)} labels found (counts don’t match).")
else:
    for i, (img_file, label_file) in enumerate(zip(images, labels)):
        # New names
        new_img_name = f"Two_Wheeler_{i}.jpg"
        new_label_name = f"Two_Wheeler_{i}.xml"

        # Old paths
        old_img_path = os.path.join(images_path, img_file)
        old_label_path = os.path.join(labels_path, label_file)

        # New paths
        new_img_path = os.path.join(images_path, new_img_name)
        new_label_path = os.path.join(labels_path, new_label_name)

        # Rename
        os.rename(old_img_path, new_img_path)
        os.rename(old_label_path, new_label_path)

        print(f"Renamed: {img_file} -> {new_img_name}, {label_file} -> {new_label_name}")

print("✅ Renaming completed!")

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# List images and labels
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
labels = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])

print(f"📂 Two_Wheeler folder currently contains:\n")
print(f"{len(images)} images inside images/")
print(f"{len(labels)} labels inside labels/")

# Show first 3 samples from each
print("\nFirst 3 images:")
for img in images[:3]:
    print("   ", img)

print("\nFirst 3 labels:")
for lbl in labels[:3]:
    print("   ", lbl)

import os
import xml.etree.ElementTree as ET

# === Paths ===
base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'
xml_path  = os.path.join(base_path, 'labels')       # XML input folder
txt_path  = os.path.join(base_path, 'labels_txt')   # TXT output folder
os.makedirs(txt_path, exist_ok=True)

# === Define classes ===
classes = ["Four_Wheeler", "Large_Vehicle", "Three_Wheeler", "Two_Wheeler", "Bicycle"]

def voc_to_yolo_box(xmin, ymin, xmax, ymax, img_w, img_h):
    x_c = (xmin + xmax) / 2.0 / img_w
    y_c = (ymin + ymax) / 2.0 / img_h
    w   = (xmax - xmin) / img_w
    h   = (ymax - ymin) / img_h
    return x_c, y_c, w, h

converted = 0
for fname in sorted(os.listdir(xml_path)):
    if not fname.endswith(".xml"):
        continue

    xml_file = os.path.join(xml_path, fname)
    tree = ET.parse(xml_file)
    root = tree.getroot()

    size = root.find("size")
    img_w = int(size.find("width").text)
    img_h = int(size.find("height").text)

    out_txt = os.path.join(txt_path, fname.replace(".xml", ".txt"))
    with open(out_txt, "w") as f:
        for obj in root.findall("object"):
            cls = obj.find("name").text.strip()
            if cls not in classes:
                continue
            cls_id = classes.index(cls)

            bb = obj.find("bndbox")
            xmin, ymin = int(bb.find("xmin").text), int(bb.find("ymin").text)
            xmax, ymax = int(bb.find("xmax").text), int(bb.find("ymax").text)

            x_c, y_c, w, h = voc_to_yolo_box(xmin, ymin, xmax, ymax, img_w, img_h)
            f.write(f"{cls_id} {x_c:.6f} {y_c:.6f} {w:.6f} {h:.6f}\n")

    converted += 1
    print(f"Converted: {fname} → {os.path.basename(out_txt)}")

print(f"\n✅ Done. Converted {converted} XML files into TXT at: {txt_path}")

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'

for root, dirs, files in os.walk(base_path):
    # Only consider files inside this folder
    if files:
        print(f"\n📂 {root}")
        for f in sorted(files)[:3]:   # first 3 files
            print("   ", f)

import os
import shutil

base_path   = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'
labels_path = os.path.join(base_path, 'labels')       # where .xml live (target for .txt too)
txt_path    = os.path.join(base_path, 'labels_txt')   # current .txt location

os.makedirs(labels_path, exist_ok=True)

copied = 0
skipped = 0
missing_txt_dir = 0

if not os.path.isdir(txt_path):
    raise FileNotFoundError(f"TXT source folder not found: {txt_path}")

for fname in os.listdir(txt_path):
    if not fname.endswith('.txt'):
        continue
    src  = os.path.join(txt_path, fname)
    dest = os.path.join(labels_path, fname)

    if os.path.exists(dest):
        # Skip to avoid overwriting existing TXT with same name
        skipped += 1
        continue

    shutil.copy2(src, dest)
    copied += 1
    print(f"Copied: {fname} → labels/")

print(f"\n✅ Done. Copied {copied} .txt files into {labels_path}. Skipped {skipped} (already existed).")

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'

for root, dirs, files in os.walk(base_path):
    # Only consider files inside this folder
    if files:
        print(f"\n📂 {root}")
        for f in sorted(files)[:3]:   # first 3 files
            print("   ", f)

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'

for root, dirs, files in os.walk(base_path):
    # Only consider files inside this folder
    if files:
        print(f"\n📂 {root}")
        for f in sorted(files)[:3]:   # first 3 files
            print("   ", f)

#Split Two Wheeler



"""Split c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler dataset into:

Two Wheeler/ train/ images/ labels/ test/ images/ labels/ valid/ images/ labels/

with proportions:

Train = 64%

Test = 20%

Val = 16%
"""

import os, shutil, math, random

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# Collect images, .txt and .xml labels
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg','.jpeg','.png'))])
txts   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.txt')])
xmls   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])

# Build dicts for lookup by stem
stems_img = {os.path.splitext(f)[0]: f for f in images}
stems_txt = {os.path.splitext(f)[0]: f for f in txts}
stems_xml = {os.path.splitext(f)[0]: f for f in xmls}

# Only keep stems that have both image + txt (+ xml optional)
shared = sorted(stems_img.keys() & stems_txt.keys())

print(f"Total matching pairs: {len(shared)}")

# Split sizes
n_total = len(shared)
n_train = math.floor(n_total * 0.64)
n_test  = math.floor(n_total * 0.20)
n_val   = n_total - n_train - n_test
print(f"Splitting → Train: {n_train}, Test: {n_test}, Val: {n_val}")

random.shuffle(shared)
train_stems = shared[:n_train]
test_stems  = shared[n_train:n_train+n_test]
val_stems   = shared[n_train+n_test:]

splits = {"train": train_stems, "test": test_stems, "valid": val_stems}

# Create output folders inside base_path
for split in splits.keys():
    for sub in ("images", "labels"):
        os.makedirs(os.path.join(base_path, split, sub), exist_ok=True)

# Move files into split folders
for split, stems in splits.items():
    for stem in stems:
        # image
        img_src = os.path.join(images_path, stems_img[stem])
        img_dst = os.path.join(base_path, split, "images", stems_img[stem])
        shutil.move(img_src, img_dst)

        # txt
        txt_src = os.path.join(labels_path, stems_txt[stem])
        txt_dst = os.path.join(base_path, split, "labels", stems_txt[stem])
        shutil.move(txt_src, txt_dst)

        # xml (only if exists for this stem)
        if stem in stems_xml:
            xml_src = os.path.join(labels_path, stems_xml[stem])
            xml_dst = os.path.join(base_path, split, "labels", stems_xml[stem])
            shutil.move(xml_src, xml_dst)

print("✅ Dataset split completed (images + txt + xml)")

folders = [f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))]

print(f"📂 Folders inside {base_path}:")
for folder in sorted(folders):
    print("   └──", folder)

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler'

for root, dirs, files in os.walk(base_path):
    # Relative path for nicer display
    rel_path = os.path.relpath(root, base_path)
    if rel_path == ".":
        rel_path = ""  # top-level

    print(f"📂 {os.path.join(base_path, rel_path)}")
    for d in dirs:
        print(f"   └── {d}")

import os
from PIL import Image
import xml.etree.ElementTree as ET
from xml.dom import minidom

# ====== CONFIG ======
LABELS_DIR = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler/labels'
IMAGES_DIR = os.path.join(os.path.dirname(LABELS_DIR), 'images')  # sibling 'images' folder

# Map YOLO class IDs to names (fill if you know them; unknowns will be "unknown")
CLASS_MAPPING = {
    # 0: 'Three_Wheeler',
    # 1: 'Two_Wheeler',
    # 2: 'Four_Wheeler',
    # ...
}
# =====================

def prettify_xml(elem) -> str:
    rough = ET.tostring(elem, 'utf-8')
    return minidom.parseString(rough).toprettyxml(indent="    ")

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def find_image_for_label(stem: str):
    for ext in ('.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG'):
        p = os.path.join(IMAGES_DIR, stem + ext)
        if os.path.exists(p):
            return p
    return None

def yolo_line_to_bbox(abs_w, abs_h, x_c, y_c, w, h):
    x_min = int(round((x_c - w/2) * abs_w))
    y_min = int(round((y_c - h/2) * abs_h))
    x_max = int(round((x_c + w/2) * abs_w))
    y_max = int(round((y_c + h/2) * abs_h))

    x_min = clamp(x_min, 0, abs_w - 1)
    y_min = clamp(y_min, 0, abs_h - 1)
    x_max = clamp(x_max, 0, abs_w - 1)
    y_max = clamp(y_max, 0, abs_h - 1)
    return x_min, y_min, x_max, y_max

def convert_one_txt(txt_path: str):
    stem = os.path.splitext(os.path.basename(txt_path))[0]
    img_path = find_image_for_label(stem)
    if not img_path:
        print(f"[WARN] No image for: {txt_path}")
        return

    try:
        with Image.open(img_path) as im:
            w, h = im.size
            depth = len(im.getbands())
    except Exception as e:
        print(f"[ERROR] Open image failed ({img_path}): {e}")
        return

    ann = ET.Element('annotation')
    ET.SubElement(ann, 'folder').text = os.path.basename(os.path.dirname(img_path))
    ET.SubElement(ann, 'filename').text = os.path.basename(img_path)

    size = ET.SubElement(ann, 'size')
    ET.SubElement(size, 'width').text  = str(w)
    ET.SubElement(size, 'height').text = str(h)
    ET.SubElement(size, 'depth').text  = str(depth)

    with open(txt_path, 'r') as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 5:
                # malformed line; skip
                continue

            try:
                cls_id = int(parts[0])
                x_c, y_c, bw, bh = map(float, parts[1:])
            except ValueError:
                continue

            xmin, ymin, xmax, ymax = yolo_line_to_bbox(w, h, x_c, y_c, bw, bh)
            if xmax <= xmin or ymax <= ymin:
                # degenerate box; skip
                continue

            obj = ET.SubElement(ann, 'object')
            ET.SubElement(obj, 'name').text = CLASS_MAPPING.get(cls_id, 'unknown')
            ET.SubElement(obj, 'pose').text = 'Unspecified'
            ET.SubElement(obj, 'truncated').text = '0'
            ET.SubElement(obj, 'difficult').text = '0'

            bnd = ET.SubElement(obj, 'bndbox')
            ET.SubElement(bnd, 'xmin').text = str(xmin)
            ET.SubElement(bnd, 'ymin').text = str(ymin)
            ET.SubElement(bnd, 'xmax').text = str(xmax)
            ET.SubElement(bnd, 'ymax').text = str(ymax)

    xml_out = os.path.join(LABELS_DIR, stem + '.xml')
    with open(xml_out, 'w') as xf:
        xf.write(prettify_xml(ann))
    print(f"[OK] {os.path.basename(txt_path)} → {os.path.basename(xml_out)}")

def main():
    if not os.path.isdir(LABELS_DIR):
        raise FileNotFoundError(f"Labels dir not found: {LABELS_DIR}")
    if not os.path.isdir(IMAGES_DIR):
        print(f"[WARN] Images dir not found: {IMAGES_DIR} (image lookup will fail)")

    txt_files = [f for f in os.listdir(LABELS_DIR) if f.lower().endswith('.txt')]
    if not txt_files:
        print("[INFO] No .txt files found.")
        return

    for fname in sorted(txt_files):
        convert_one_txt(os.path.join(LABELS_DIR, fname))

    print("\n✅ Done converting all .txt to .xml in:", LABELS_DIR)

if __name__ == "__main__":
    main()

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# Collect files
images = [f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
txts   = [f for f in os.listdir(labels_path) if f.lower().endswith('.txt')]
xmls   = [f for f in os.listdir(labels_path) if f.lower().endswith('.xml')]

# Build maps by stem
img_map = {os.path.splitext(f)[0]: f for f in images}
txt_map = {os.path.splitext(f)[0]: f for f in txts}
xml_map = {os.path.splitext(f)[0]: f for f in xmls}

# Match stems that have at least image + txt
shared_stems = sorted(img_map.keys() & txt_map.keys())

print(f"Found {len(shared_stems)} matching sets (image + txt [+xml]).")

for i, stem in enumerate(shared_stems):
    # Old paths
    old_img = os.path.join(images_path, img_map[stem])
    old_txt = os.path.join(labels_path, txt_map[stem])
    old_xml = os.path.join(labels_path, xml_map[stem]) if stem in xml_map else None

    # New names
    new_img = os.path.join(images_path, f"Three_Wheeler_{i}.JPG")
    new_txt = os.path.join(labels_path, f"Three_Wheeler_{i}.txt")
    new_xml = os.path.join(labels_path, f"Three_Wheeler_{i}.xml") if old_xml else None

    # Rename (skip if already renamed or destination exists)
    if os.path.exists(old_img) and not os.path.exists(new_img):
        os.rename(old_img, new_img)
    if os.path.exists(old_txt) and not os.path.exists(new_txt):
        os.rename(old_txt, new_txt)
    if old_xml and os.path.exists(old_xml) and not os.path.exists(new_xml):
        os.rename(old_xml, new_xml)

    # Log
    print(f"{img_map[stem]} → {os.path.basename(new_img)}")
    print(f"{txt_map[stem]} → {os.path.basename(new_txt)}")
    if old_xml:
        print(f"{xml_map[stem]} → {os.path.basename(new_xml)}")

print("✅ Renaming completed (images + txt + xml).")

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# List sorted files
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
txts   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.txt')])
xmls   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])

print("📂 First 3 images:")
for img in images[:3]:
    print("   ", img)

print("\n📂 First 3 .txt labels:")
for lbl in txts[:3]:
    print("   ", lbl)

print("\n📂 First 3 .xml labels:")
for xml in xmls[:3]:
    print("   ", xml)

"""Split the already-renamed Three_Wheeler/images and Three Wheeler/labels into a dataset structure like this:

train/ images/ labels/ test/ images/ labels/ valid/ images/ labels/

with proportions:

Train: 64%

Test: 20%

Val: 16%
"""

import os, shutil, math, random
from collections import Counter

base_path   = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# --- Collect files ---
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
txts   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.txt')])
xmls   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])

# Map by stem
stems_img = {os.path.splitext(f)[0]: f for f in images}
stems_txt = {os.path.splitext(f)[0]: f for f in txts}
stems_xml = {os.path.splitext(f)[0]: f for f in xmls}  # optional

# Use samples that have BOTH image + .txt label
shared = sorted(stems_img.keys() & stems_txt.keys())
print(f"Total matching image+.txt pairs: {len(shared)}")

# --- Splits (64/20/16) ---
n_total = len(shared)
n_train = math.floor(n_total * 0.64)
n_test  = math.floor(n_total * 0.20)
n_val   = n_total - n_train - n_test
print(f"Splitting → Train: {n_train}, Test: {n_test}, Val: {n_val}")

random.shuffle(shared)
train_stems = shared[:n_train]
test_stems  = shared[n_train:n_train+n_test]
val_stems   = shared[n_train+n_test:]

splits = {"train": train_stems, "test": test_stems, "valid": val_stems}

# --- Create output folders ---
out_base = os.path.join(base_path, "split_dataset")
for split in splits.keys():
    for sub in ("images", "labels"):
        os.makedirs(os.path.join(out_base, split, sub), exist_ok=True)

# --- Copy files (image + txt + optional xml) ---
stats = Counter()
for split, stems in splits.items():
    for stem in stems:
        # image
        img_src = os.path.join(images_path, stems_img[stem])
        img_dst = os.path.join(out_base, split, "images", stems_img[stem])
        shutil.copy2(img_src, img_dst)
        stats[(split, 'images')] += 1

        # txt
        txt_src = os.path.join(labels_path, stems_txt[stem])
        txt_dst = os.path.join(out_base, split, "labels", stems_txt[stem])
        shutil.copy2(txt_src, txt_dst)
        stats[(split, 'txt')] += 1

        # xml (if available for this stem)
        if stem in stems_xml:
            xml_src = os.path.join(labels_path, stems_xml[stem])
            xml_dst = os.path.join(out_base, split, "labels", stems_xml[stem])
            shutil.copy2(xml_src, xml_dst)
            stats[(split, 'xml')] += 1

print("✅ Dataset split completed!")
print("Structure created under:", out_base)

# Optional: quick summary
for split in ['train', 'test', 'valid']:
    imgs = stats[(split, 'images')]
    txtn = stats[(split, 'txt')]
    xmln = stats[(split, 'xml')]
    print(f"- {split}: {imgs} images, {txtn} txt, {xmln} xml")

import os, shutil
from collections import Counter

base_path   = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler'
split_path  = os.path.join(base_path, 'split_dataset')
splits      = ['train', 'test', 'valid']
subfolders  = ['images', 'labels']

def ensure_dirs(path):
    os.makedirs(path, exist_ok=True)

def move_or_merge_folder(src, dst):
    """
    Merge contents of src into dst (creates dst if missing).
    Moves files recursively, including .txt and .xml in labels/.
    """
    ensure_dirs(dst)
    stats = Counter()
    for root, dirs, files in os.walk(src):
        rel = os.path.relpath(root, src)
        target_root = os.path.join(dst, rel) if rel != '.' else dst
        ensure_dirs(target_root)

        for f in files:
            src_f = os.path.join(root, f)
            dst_f = os.path.join(target_root, f)

            # If a file with same name exists, overwrite to keep split_dataset as source of truth
            if os.path.exists(dst_f):
                os.remove(dst_f)

            shutil.move(src_f, dst_f)

            # Count types for quick summary
            low = f.lower()
            if target_root.endswith('labels'):
                if low.endswith('.xml'):
                    stats['xml'] += 1
                elif low.endswith('.txt'):
                    stats['txt'] += 1
            elif target_root.endswith('images'):
                stats['img'] += 1

    # Clean up emptied directories
    for root, dirs, files in sorted(os.walk(src, topdown=False)):
        if not os.listdir(root):
            os.rmdir(root)
    return stats

# --- main ---
if not os.path.exists(split_path):
    raise FileNotFoundError(f"{split_path} does not exist. Did you already move them?")

overall = {}
for split in splits:
    src = os.path.join(split_path, split)
    dst = os.path.join(base_path, split)

    if not os.path.exists(src):
        print(f"⚠️ Missing: {src}, skipping.")
        continue

    if os.path.exists(dst):
        print(f"ℹ️ {dst} exists → merging {src} into it...")
        stats = move_or_merge_folder(src, dst)
        overall[split] = stats
        print(f"   Merged {split}: {stats['img']} images, {stats['txt']} txt, {stats['xml']} xml")
    else:
        shutil.move(src, dst)
        # quick count after move
        imgs = sum(len([f for f in files if f.lower().endswith(('.jpg','.jpeg','.png'))])
                   for _, _, files in os.walk(os.path.join(dst, 'images'))) if os.path.exists(os.path.join(dst,'images')) else 0
        txts = sum(len([f for f in files if f.lower().endswith('.txt')])
                   for _, _, files in os.walk(os.path.join(dst, 'labels'))) if os.path.exists(os.path.join(dst,'labels')) else 0
        xmls = sum(len([f for f in files if f.lower().endswith('.xml')])
                   for _, _, files in os.walk(os.path.join(dst, 'labels'))) if os.path.exists(os.path.join(dst,'labels')) else 0
        overall[split] = Counter({'img': imgs, 'txt': txts, 'xml': xmls})
        print(f"Moved {split}/ → {dst}  ({imgs} images, {txts} txt, {xmls} xml)")

# Try removing empty split_dataset
try:
    os.rmdir(split_path)
    print(f"Removed empty folder: {split_path}")
except OSError:
    print(f"⚠️ Could not remove {split_path} (not empty).")

print("\n✅ Done. train/test/valid now under:", base_path)
for split in splits:
    if split in overall:
        s = overall[split]
        print(f"- {split}: {s['img']} images, {s['txt']} txt, {s['xml']} xml")

folders = [f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))]

print(f"📂 Folders inside {base_path}:")
for folder in sorted(folders):
    print("   └──", folder)

#Four Wheeler

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Four Wheeler'

for root, dirs, files in os.walk(base_path):
    # Make relative path for pretty print
    rel_path = os.path.relpath(root, base_path)
    if rel_path == ".":
        rel_path = ""  # top-level

    print(f"📂 {os.path.join(base_path, rel_path)}")
    for d in dirs:
        print(f"   └── {d}")

"""move the split dataset from Four Wheeler/car_dataset-master/ to Four Wheeler/ Four Wheeler/ train/ test/ valid/"""

import os, shutil

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Four Wheeler'
nested_path = os.path.join(base_path, 'car_dataset-master')

for split in ['train', 'test', 'valid']:
    src = os.path.join(nested_path, split)
    dst = os.path.join(base_path, split)

    if os.path.exists(src):
        if os.path.exists(dst):
            print(f"⚠️ Destination already exists, skipping: {dst}")
        else:
            shutil.move(src, dst)
            print(f"Moved {split}/ → {dst}")
    else:
        print(f"⚠️ Source not found: {src}")

# remove the now-empty car_dataset-master if it has nothing left
try:
    os.rmdir(nested_path)
    print(f"🗑️ Removed empty folder: {nested_path}")
except OSError:
    print(f"⚠️ {nested_path} not empty, not removed.")

print("✅ Done. train/test/valid are now directly under Four Wheeler/")

folders = [f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))]

print(f"📂 Folders inside {base_path}:")
for folder in sorted(folders):
    print("   └──", folder)

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Four Wheeler'
target = os.path.join(base_path, 'car_dataset-master')

if os.path.isdir(target):
    if not os.listdir(target):  # empty folder check
        os.rmdir(target)
        print(f"✅ Removed empty folder: {target}")
    else:
        print(f"⚠️ Folder not empty, skipping: {target}")
else:
    print(f"ℹ️ No such folder: {target}")

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Four Wheeler'
splits = ['train', 'test', 'valid']

def list_first3(dir_path, exts):
    try:
        return sorted([f for f in os.listdir(dir_path) if f.lower().endswith(exts)])[:3]
    except FileNotFoundError:
        return None

for split in splits:
    images_path = os.path.join(base_path, split, 'images')
    labels_path = os.path.join(base_path, split, 'labels')

    imgs = list_first3(images_path, ('.jpg', '.jpeg', '.png'))
    txts = list_first3(labels_path, ('.txt',))
    xmls = list_first3(labels_path, ('.xml',))

    print(f"\n=== {split.upper()} ===")
    if imgs is None and txts is None and xmls is None:
        print(f"⚠️ Missing both images/ and labels/ under {os.path.join(base_path, split)}")
        continue

    print("📂 First 3 images:")
    print("   (none)" if not imgs else "\n".join(f"   {x}" for x in imgs))

    print("📂 First 3 .txt labels:")
    print("   (none)" if not txts else "\n".join(f"   {x}" for x in txts))

    print("📂 First 3 .xml labels:")
    print("   (none)" if not xmls else "\n".join(f"   {x}" for x in xmls))

#Large Vehicles

"""Rename matching image/label pairs in this order: train → test → valid, keeping a single running counter so filenames are unique across all splits.

What to do:

Pair by basename (so 000001.jpg ↔ 000001.txt).

Rename to Four Wheeler_.jpg / .txt (with a space, as in the example).

Skip any unpaired files.

Avoid collisions with a temporary move.
"""

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'

for root, dirs, files in os.walk(base_path):
    # Path relative to base for cleaner display
    rel = os.path.relpath(root, base_path)
    if rel == ".":
        rel = ""  # top-level

    print(f"📂 {os.path.join(base_path, rel)}")
    for d in dirs:
        print(f"   └── {d}")

#Merge Tractor and Truck folder into one Image and Label folder

"""Here’s a safe script that:

Gathers only matching pairs from Tractor and Truck

Writes them into Large_Vehicle/images & Large_Vehicle/labels

Uses continuous numbering Large_Vehicle_0..N

Lets you force .jpg (set FORCE_IMG_EXT=None to keep original) merged pairs renamed sequentially as:

Large_Vehicle/images/Large_Vehicle_0.jpg Large_Vehicle/labels/Large_Vehicle_0.txt Large_Vehicle_1.*, ...

Merge Tractor + Truck into Large_Vehicle/images and Large_Vehicle/labels

Moves/copies only matching pairs (same basename).

Keeps original extensions.

Prevents collisions (if a name already exists, it prefixes with the source name and, if needed, adds a numeric suffix).

Set MOVE_FILES=True to move, False to copy.
"""

# --- SCRIPT 1: MERGE INTO Large_Vehicle/images & labels (keep .txt AND .xml) ---

import os, shutil

BASE = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'
SOURCES = ['Tractor', 'Truck', 'truck']   # supports either capitalization
TARGET_IMAGES = os.path.join(BASE, 'images')
TARGET_LABELS = os.path.join(BASE, 'labels')
MOVE_FILES = True                          # set to False to COPY instead of MOVE

IMG_EXTS   = ('.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG')
LABEL_EXTS = ('.txt', '.xml')

os.makedirs(TARGET_IMAGES, exist_ok=True)
os.makedirs(TARGET_LABELS, exist_ok=True)

def move_or_copy(src, dst):
    if MOVE_FILES: shutil.move(src, dst)
    else: shutil.copy2(src, dst)

def all_targets_free(base_stem, img_ext, lbl_exts_present):
    """
    Check if the image destination and ALL label destinations for the given stem are free.
    """
    # image path
    img_dst = os.path.join(TARGET_IMAGES, base_stem + img_ext)
    if os.path.exists(img_dst):
        return False
    # every label ext present must be free
    for le in lbl_exts_present:
        if os.path.exists(os.path.join(TARGET_LABELS, base_stem + le)):
            return False
    return True

def choose_unique_base_stem(orig_stem, img_ext, lbl_exts_present, src_tag):
    """
    Find a unique base stem such that:
    - {TARGET_IMAGES}/{stem}{img_ext} doesn't exist, and
    - {TARGET_LABELS}/{stem}{each label ext present} doesn't exist.
    Strategy: try plain stem, then <src_tag>_<stem>, then add _1, _2, ...
    Returns the chosen base stem string.
    """
    # 1) try plain stem
    if all_targets_free(orig_stem, img_ext, lbl_exts_present):
        return orig_stem

    # 2) try prefixed with source tag
    pref = f"{src_tag}_{orig_stem}"
    if all_targets_free(pref, img_ext, lbl_exts_present):
        return pref

    # 3) add counters
    i = 1
    while True:
        s = f"{pref}_{i}"
        if all_targets_free(s, img_ext, lbl_exts_present):
            return s
        i += 1

total_images = 0
labels_copied = 0
unpaired_imgs = 0
unpaired_lbls = 0

for src in SOURCES:
    src_root = os.path.join(BASE, src)
    img_dir  = os.path.join(src_root, 'images')
    lbl_dir  = os.path.join(src_root, 'labels')
    if not (os.path.isdir(img_dir) and os.path.isdir(lbl_dir)):
        continue

    imgs = [f for f in os.listdir(img_dir) if f.endswith(IMG_EXTS)]
    lbls = [f for f in os.listdir(lbl_dir) if f.endswith(LABEL_EXTS)]

    # Map by stem
    img_map = {os.path.splitext(f)[0]: f for f in imgs}

    # labels: keep ALL (.txt and/or .xml) for each stem
    lbl_map_multi = {}
    for f in lbls:
        stem, ext = os.path.splitext(f)
        lbl_map_multi.setdefault(stem, []).append(f)

    # stems with both image and at least one label
    shared_stems = sorted(set(img_map) & set(lbl_map_multi))

    # stats for unpaired
    only_imgs = set(img_map) - set(lbl_map_multi)
    only_lbls = set(lbl_map_multi) - set(img_map)
    unpaired_imgs += len(only_imgs)
    unpaired_lbls += len(only_lbls)

    for stem in shared_stems:
        img_name = img_map[stem]
        label_files = lbl_map_multi[stem]  # could contain one or both of .txt/.xml

        img_src  = os.path.join(img_dir, img_name)
        img_ext  = os.path.splitext(img_name)[1]

        # which label extensions exist for this stem (preserve original ext cases)
        lbl_exts_present = [os.path.splitext(f)[1] for f in label_files]

        # choose a base stem that keeps image + ALL labels collision-free
        base_stem = choose_unique_base_stem(stem, img_ext, lbl_exts_present, src_tag=src.replace(' ', '_'))

        # copy/move image once
        img_dst = os.path.join(TARGET_IMAGES, base_stem + img_ext)
        move_or_copy(img_src, img_dst)
        total_images += 1

        # copy/move each label file (.txt and/or .xml)
        for lbl_name in label_files:
            lbl_src = os.path.join(lbl_dir, lbl_name)
            lbl_ext = os.path.splitext(lbl_name)[1]
            lbl_dst = os.path.join(TARGET_LABELS, base_stem + lbl_ext)
            move_or_copy(lbl_src, lbl_dst)
            labels_copied += 1

print(f"✅ Merge complete.")
print(f"   Images moved/copied: {total_images}")
print(f"   Labels moved/copied: {labels_copied} (includes .txt and .xml)")
print(f"   Unpaired images (no label): {unpaired_imgs}")
print(f"   Unpaired labels (no image): {unpaired_lbls}")
print("Targets:")
print("  ", TARGET_IMAGES)
print("  ", TARGET_LABELS)

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'

for root, dirs, files in os.walk(base_path):
    # Path relative to base for cleaner display
    rel = os.path.relpath(root, base_path)
    if rel == ".":
        rel = ""  # top-level

    print(f"📂 {os.path.join(base_path, rel)}")
    for d in dirs:
        print(f"   └── {d}")

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'  # or 'Large_Vehicle'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# List sorted files
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg','.jpeg','.png'))])
labels = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])

print("📂 First 5 images:")
for img in images[:5]:
    print("   ", img)

print("\n📂 First 5 labels:")
for lbl in labels[:5]:
    print("   ", lbl)

#Renaming

"""images/Four_Wheeler_0.jpg

labels/Four_Wheeler_0.xml
"""

import os, re, shutil

base_path   = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# Collect
imgs = [f for f in os.listdir(images_path) if f.lower().endswith(('.jpg','.jpeg','.png'))]
xmls = [f for f in os.listdir(labels_path) if f.lower().endswith('.xml')]

# Pair by stem
img_map = {os.path.splitext(f)[0]: f for f in imgs}
xml_map = {os.path.splitext(f)[0]: f for f in xmls}
nkey = lambda s: [int(t) if t.isdigit() else s.lower() for t in re.split(r'(\d+)', s)]
shared = sorted(img_map.keys() & xml_map.keys(), key=nkey)

# Stage to avoid collisions
tmp_i = os.path.join(base_path, '.tmp_i'); os.makedirs(tmp_i, exist_ok=True)
tmp_l = os.path.join(base_path, '.tmp_l'); os.makedirs(tmp_l, exist_ok=True)
for stem in shared:
    shutil.move(os.path.join(images_path, img_map[stem]), os.path.join(tmp_i, img_map[stem]))
    shutil.move(os.path.join(labels_path, xml_map[stem]), os.path.join(tmp_l,  xml_map[stem]))

# Rename back sequentially
for i, stem in enumerate(shared):
    img_ext = os.path.splitext(img_map[stem])[1].lower()   # keep original image ext
    shutil.move(os.path.join(tmp_i, img_map[stem]), os.path.join(images_path, f'Large_Vehicle_{i}{img_ext}'))
    shutil.move(os.path.join(tmp_l,  xml_map[stem]), os.path.join(labels_path,  f'Large_Vehicle_{i}.xml'))

# Cleanup temps
for p in (tmp_i, tmp_l):
    try: os.rmdir(p)
    except OSError: pass

# Preview
print("📂 First 3 images:", sorted(os.listdir(images_path), key=nkey)[:3])
print("📂 First 3 labels:", sorted(os.listdir(labels_path), key=nkey)[:3])

import os
import xml.etree.ElementTree as ET

# === Paths ===
base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'
xml_path  = os.path.join(base_path, 'labels')       # XML input folder
txt_path  = os.path.join(base_path, 'labels_txt')   # TXT output folder
os.makedirs(txt_path, exist_ok=True)

# === Define classes ===
# Only one class in your dataset
classes = ["Large_Vehicle"]

def voc_to_yolo_box(xmin, ymin, xmax, ymax, img_w, img_h):
    """
    Convert Pascal VOC bbox to YOLO format:
    (xmin, ymin, xmax, ymax) -> (x_center, y_center, width, height), normalized 0-1
    """
    x_c = (xmin + xmax) / 2.0 / img_w
    y_c = (ymin + ymax) / 2.0 / img_h
    w   = (xmax - xmin) / img_w
    h   = (ymax - ymin) / img_h
    return x_c, y_c, w, h

converted = 0
for fname in sorted(os.listdir(xml_path)):
    if not fname.endswith(".xml"):
        continue

    xml_file = os.path.join(xml_path, fname)
    tree = ET.parse(xml_file)
    root = tree.getroot()

    # Get image dimensions
    size = root.find("size")
    img_w = int(size.find("width").text)
    img_h = int(size.find("height").text)

    # Create output .txt file path
    out_txt = os.path.join(txt_path, fname.replace(".xml", ".txt"))
    with open(out_txt, "w") as f:
        for obj in root.findall("object"):
            # Kaggle labels often say 'tractor' or 'truck', we force Large Vehicle class (1)
            cls_id = 1

            bb = obj.find("bndbox")
            xmin, ymin = float(bb.find("xmin").text), float(bb.find("ymin").text)
            xmax, ymax = float(bb.find("xmax").text), float(bb.find("ymax").text)

            # Convert VOC bbox -> YOLO format
            x_c, y_c, w, h = voc_to_yolo_box(xmin, ymin, xmax, ymax, img_w, img_h)

            # Write YOLO line: class_id x_center y_center width height
            f.write(f"{cls_id} {x_c:.6f} {y_c:.6f} {w:.6f} {h:.6f}\n")

    converted += 1
    print(f"Converted: {fname} → {os.path.basename(out_txt)}")

print(f"\n✅ Done. Converted {converted} XML files into TXT at: {txt_path}")

import shutil, os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'
txt_src   = os.path.join(base_path, 'labels_txt')
txt_dst   = os.path.join(base_path, 'labels')

for f in os.listdir(txt_src):
    if f.endswith('.txt'):
        shutil.move(os.path.join(txt_src, f), os.path.join(txt_dst, f))
print("✅ Moved all .txt files into labels/")

import os

base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'  # or 'Large_Vehicle'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# List sorted files
images = sorted([f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
xmls   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.xml')])
txts   = sorted([f for f in os.listdir(labels_path) if f.lower().endswith('.txt')])

print("📂 First 5 images:")
for img in images[:5]:
    print("   ", img)

print("\n📂 First 5 .xml labels:")
for lbl in xmls[:5]:
    print("   ", lbl)

print("\n📂 First 5 .txt labels:")
for lbl in txts[:5]:
    print("   ", lbl)

"""#split Large Vehicle into train/test/valid with 64/20/16 (moves only matching image↔label pairs"""

import os, shutil, random, math

base_path   = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle'
images_path = os.path.join(base_path, 'images')
labels_path = os.path.join(base_path, 'labels')

# Collect matching pairs by basename
imgs = [f for f in os.listdir(images_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
txts = [f for f in os.listdir(labels_path) if f.lower().endswith('.txt')]
xmls = [f for f in os.listdir(labels_path) if f.lower().endswith('.xml')]

img_map = {os.path.splitext(f)[0]: f for f in imgs}
txt_map = {os.path.splitext(f)[0]: f for f in txts}
xml_map = {os.path.splitext(f)[0]: f for f in xmls}  # optional

# Use samples that have BOTH image + .txt label; include .xml if present
shared = sorted(img_map.keys() & txt_map.keys())

# Shuffle + compute split sizes
random.shuffle(shared)
n = len(shared)
n_train = math.floor(n * 0.64)
n_test  = math.floor(n * 0.20)
n_valid = n - n_train - n_test

splits = {
    'train': shared[:n_train],
    'test':  shared[n_train:n_train+n_test],
    'valid': shared[n_train+n_test:]
}

# Make folders
for s in splits:
    os.makedirs(os.path.join(base_path, s, 'images'), exist_ok=True)
    os.makedirs(os.path.join(base_path, s, 'labels'), exist_ok=True)

# Move files (image + .txt + optional .xml)
for s, stems in splits.items():
    for stem in stems:
        # image
        shutil.move(
            os.path.join(images_path, img_map[stem]),
            os.path.join(base_path, s, 'images', img_map[stem])
        )
        # txt
        shutil.move(
            os.path.join(labels_path, txt_map[stem]),
            os.path.join(base_path, s, 'labels', txt_map[stem])
        )
        # xml (if available for this stem)
        if stem in xml_map:
            shutil.move(
                os.path.join(labels_path, xml_map[stem]),
                os.path.join(base_path, s, 'labels', xml_map[stem])
            )

print(f"✅ Done. total={n} -> train={n_train} (64%), test={n_test} (20%), valid={n_valid} (16%)")

import os

root = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

# resolve path variant
base_path = None
for cand in ('Large Vehicle', 'Large_Vehicle'):
    p = os.path.join(root, cand)
    if os.path.isdir(p):
        base_path = p
        break
if base_path is None:
    raise FileNotFoundError("Large Vehicle/_Vehicle not found")

# list only directories
folders = sorted([f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))])

print(f"📂 Folders inside {base_path}:")
for f in folders:
    print("   └──", f)

import os

base = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
print(f"📂 {base}")

for name in sorted(os.listdir(base)):
    p = os.path.join(base, name)
    tag = "📁" if os.path.isdir(p) else "📄"
    print(f"  {tag} {name}")

for name in sorted(d for d in os.listdir(base) if os.path.isdir(os.path.join(base, d))):
    print("  📁", name)

import os

base = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

def walk_dirs(path, prefix=""):
    try:
        dirs = sorted(d for d in os.listdir(path) if os.path.isdir(os.path.join(path, d)))
    except FileNotFoundError:
        print("Path not found:", path); return
    for i, d in enumerate(dirs):
        last = (i == len(dirs) - 1)
        print(f"{prefix}{'└──' if last else '├──'} {d}")
        walk_dirs(os.path.join(path, d), prefix + ("    " if last else "│   "))

print(f"📂 {base}")
walk_dirs(base)

import os, shutil

base = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
target = os.path.join(base, 'Large_Vehicle')  # underscored version

if os.path.isdir(target):
    shutil.rmtree(target)
    print(f"🗑️ Removed: {target}")
else:
    print(f"⚠️ Not found (skipped): {target}")

# Optional: show remaining top-level folders
print(f"\n📂 {base}")
for name in sorted(d for d in os.listdir(base) if os.path.isdir(os.path.join(base, d))):
    print("  📁", name)

print(f"📂 {base}")
walk_dirs(base)

# Path to your dataset
dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

# List the contents of the dataset directory
dataset_files = os.listdir(dataset_path)

# Display the contents
dataset_files

# List subdirectories ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']
subfolders = {}

for vehicle in vehicle_types:
    subfolders[vehicle] = os.listdir(os.path.join(dataset_path, vehicle))

subfolders

#import os

# Path to the main dataset directory
dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

# Vehicle folders
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']

# Count total files in each main folder (including all subfolders)
folder_counts = {}

for vehicle in vehicle_types:
    vehicle_folder = os.path.join(dataset_path, vehicle)
    total_files = 0

    # Walk through the folder and sum up all files
    for root, dirs, files in os.walk(vehicle_folder):
        total_files += len(files)

    folder_counts[vehicle] = total_files

folder_counts

import os

dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']

def count_files(path):
    return sum(len(files) for _, _, files in os.walk(path)) if os.path.isdir(path) else 0

file_counts = {}

for vehicle in vehicle_types:
    vbase = os.path.join(dataset_path, vehicle)
    splits = {}
    for split in ['train', 'test', 'valid']:   # folder is "valid", not "val"
        sbase = os.path.join(vbase, split)
        n_img = count_files(os.path.join(sbase, 'images'))
        n_lbl = count_files(os.path.join(sbase, 'labels'))
        splits[split] = {'images': n_img, 'labels': n_lbl, 'total': n_img + n_lbl}
    file_counts[vehicle] = splits

print(file_counts)

import os

dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']

def count_files(path):
    return sum(len(files) for _, _, files in os.walk(path)) if os.path.isdir(path) else 0

def split_dir(vbase, split):
    if split != 'valid':
        p = os.path.join(vbase, split)
        return p if os.path.isdir(p) else None
    # valid can be 'valid' or 'val'
    for name in ('valid', 'val'):
        p = os.path.join(vbase, name)
        if os.path.isdir(p): return p
    return None

file_counts, file_percentages = {}, {}

for vehicle in vehicle_types:
    vbase = os.path.join(dataset_path, vehicle)
    splits = {}
    for split in ['train', 'test', 'valid']:
        sdir = split_dir(vbase, split)
        n_img = count_files(os.path.join(sdir, 'images')) if sdir else 0
        n_lbl = count_files(os.path.join(sdir, 'labels')) if sdir else 0
        total = n_img + n_lbl
        splits[split] = {'images': n_img, 'labels': n_lbl, 'total': total}
    file_counts[vehicle] = splits

    t = sum(s['total'] for s in splits.values())
    file_percentages[vehicle] = {
        'train': f"{(splits['train']['total']/t*100):.2f}%" if t else "0%",
        'test':  f"{(splits['test']['total']/t*100):.2f}%" if t else "0%",
        'val':   f"{(splits['valid']['total']/t*100):.2f}%" if t else "0%",
        'total': '100%' if t else '0%'
    }

print(file_counts)
print(file_percentages)

import os

dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']

IMG_EXTS = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')

def split_dir(vbase, split):
    if split == 'val':
        for name in ('val', 'valid'):
            p = os.path.join(vbase, name)
            if os.path.isdir(p): return p
        return None
    p = os.path.join(vbase, split)
    return p if os.path.isdir(p) else None

def count_images(sdir):
    if not sdir: return 0
    images_dir = os.path.join(sdir, 'images')
    if os.path.isdir(images_dir):
        return sum(1 for f in os.listdir(images_dir) if f.lower().endswith(IMG_EXTS))
    return sum(1 for f in os.listdir(sdir) if f.lower().endswith(IMG_EXTS))

counts = {}
percents = {}

for vehicle in vehicle_types:
    vbase = os.path.join(dataset_path, vehicle)
    n_train = count_images(split_dir(vbase, 'train'))
    n_test  = count_images(split_dir(vbase, 'test'))
    n_val   = count_images(split_dir(vbase, 'val'))
    total   = n_train + n_test + n_val

    counts[vehicle] = {'train': n_train, 'test': n_test, 'val': n_val, 'total': total}
    percents[vehicle] = (
        {'train': f"{n_train/total*100:.2f}%", 'test': f"{n_test/total*100:.2f}%", 'val': f"{n_val/total*100:.2f}%", 'total': '100%'}
        if total else {'train': '0%', 'test': '0%', 'val': '0%', 'total': '0%'}
    )

print((counts, percents))

import os

dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']
IMG_EXTS = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')

def split_dir(vbase, name):
    if name == 'val':
        for n in ('val', 'valid'):
            p = os.path.join(vbase, n)
            if os.path.isdir(p): return p
        return None
    p = os.path.join(vbase, name)
    return p if os.path.isdir(p) else None

def count_images(sdir):
    if not sdir: return 0
    imgs = os.path.join(sdir, 'images')
    if os.path.isdir(imgs):
        return sum(1 for f in os.listdir(imgs) if f.lower().endswith(IMG_EXTS))
    return sum(1 for f in os.listdir(sdir) if f.lower().endswith(IMG_EXTS))

counts, percents = {}, {}

for v in vehicle_types:
    vbase = os.path.join(dataset_path, v)
    n_train = count_images(split_dir(vbase, 'train'))
    n_test  = count_images(split_dir(vbase, 'test'))
    n_val   = count_images(split_dir(vbase, 'val'))
    total   = n_train + n_test + n_val
    counts[v] = {'train': n_train, 'test': n_test, 'val': n_val, 'total': total}
    percents[v] = (
        {'train': f'{n_train/total*100:.2f}%', 'test': f'{n_test/total*100:.2f}%', 'val': f'{n_val/total*100:.2f}%', 'total': '100%'}
        if total else {'train': '0%', 'test': '0%', 'val': '0%', 'total': '0%'}
    )

# Print in the requested "horizontal" tuple format
print((counts, percents))
# If you want strictly single-line output, use:
# print(repr((counts, percents)).replace('\n', ' '))

"""To ensure that the images are valid and the dataset is correctly structured, you can preview a few images from the train and test directories."""

import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Your dataset & structure
dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'
vehicle = 'Four Wheeler'      # <- change to 'Large Vehicle', 'Three Wheeler', 'Two Wheeler'
split = 'train'               # <- change to 'test' or 'valid' if you want

images_dir = os.path.join(dataset_path, vehicle, split, 'images')
images = sorted([f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg','.jpeg','.png'))])

# Preview the first image
img = mpimg.imread(os.path.join(images_dir, images[0]))
plt.imshow(img)
plt.axis('off')
plt.show()

"""Implementing and Training the Models

**YOLOv11 Implementation (Ultralytics)

Train YOLOv11 using the CLI:**
"""

#Step 1: Create your working folder

# Commented out IPython magic to ensure Python compatibility.
# Set your working directory on Google Drive
base_dir = './data'
os.makedirs(base_dir, exist_ok=True)
# %cd $base_dir

# Download YOLOv11 small model weights
# !wget -O yolov11s.pt https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s.pt

#5. Check if the model has been downloaded (you should see 'yolov11s.pt' in your folder)
# !ls

#create the data.yaml file

import os

base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample"
splits = ["train","valid","test"]
roots  = ["Four Wheeler","Large Vehicle","Three Wheeler","Two Wheeler"]

max_id = -1
count  = 0
for r in roots:
    for s in splits:
        d = os.path.join(base, r, s, "labels")
        if not os.path.isdir(d): continue
        for f in os.listdir(d):
            if not f.endswith(".txt"): continue
            with open(os.path.join(d, f)) as fh:
                for ln in fh:
                    ln = ln.strip()
                    if not ln: continue
                    cid = int(ln.split()[0])
                    max_id = max(max_id, cid)
                    count += 1

print("Label lines scanned:", count)
print("Max class id found:", max_id)

import os

base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler"
splits = ["train", "valid", "test"]

found = []
for split in splits:
    lbl_dir = os.path.join(base, split, "labels")
    if not os.path.isdir(lbl_dir):
        continue

    for f in os.listdir(lbl_dir):
        if not f.endswith(".txt"):
            continue
        p = os.path.join(lbl_dir, f)
        with open(p) as fh:
            lines = [ln.strip() for ln in fh if ln.strip()]
        for ln in lines:
            parts = ln.split()
            if parts[0] == "4":   # look for class id 4
                found.append((p, ln))

print(f"⚠️ Found {len(found)} annotations with class id 4 in Two Wheeler.")
for path, ln in found[:15]:  # show the first 15 hits
    print(path, "→", ln)

import os, shutil

base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler"
splits = ["train","valid","test"]

backup_root = os.path.join(base, "_labels_backup_id4")
os.makedirs(backup_root, exist_ok=True)

changed_files = 0
replaced = 0

for split in splits:
    lbl_dir = os.path.join(base, split, "labels")
    if not os.path.isdir(lbl_dir):
        continue

    for f in os.listdir(lbl_dir):
        if not f.lower().endswith(".txt"):
            continue
        p = os.path.join(lbl_dir, f)
        with open(p, "r") as fh:
            lines = [ln.strip() for ln in fh if ln.strip()]

        new_lines = []
        touched = False
        for ln in lines:
            parts = ln.split()
            if parts and parts[0] == "4":     # remap class id 4 -> 3
                parts[0] = "3"
                replaced += 1
                touched = True
            new_lines.append(" ".join(parts))

        if touched:
            # backup once per file
            dst = os.path.join(backup_root, split)
            os.makedirs(dst, exist_ok=True)
            shutil.copy2(p, os.path.join(dst, f))

            with open(p, "w") as fh:
                fh.write("\n".join(new_lines) + ("\n" if new_lines else ""))
            changed_files += 1

print(f"✅ Remapped {replaced} instances of class 4 → 3 in {changed_files} files (Two Wheeler).")

import os
base_all = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample"
for d in ["Four Wheeler","Large Vehicle","Three Wheeler","Two Wheeler"]:
    for sp in ["train","valid","test"]:
        cache = os.path.join(base_all, d, sp, "labels.cache")
        if os.path.exists(cache):
            os.remove(cache); print("🧹 removed", cache)

import os
base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Two Wheeler"
splits = ["train","valid","test"]

max_id = -1; counts = {}
for sp in splits:
    d = os.path.join(base, sp, "labels")
    if not os.path.isdir(d): continue
    for f in os.listdir(d):
        if not f.endswith(".txt"): continue
        for ln in open(os.path.join(d, f)):
            ln = ln.strip()
            if not ln: continue
            cid = int(ln.split()[0])
            max_id = max(max_id, cid)
            counts[cid] = counts.get(cid, 0) + 1

print("Max class id in Two Wheeler:", max_id)
print("Per-class counts in Two Wheeler:", counts)
# Expect max_id <= 3 now

import os

base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample"
roots = ["Four Wheeler","Large Vehicle","Three Wheeler","Two Wheeler"]
splits = ["train","valid","test"]
valid_ids = {0,1,2,3}   # since nc=4

bad = []
for r in roots:
    for s in splits:
        d = os.path.join(base, r, s, "labels")
        if not os.path.isdir(d): continue
        for f in os.listdir(d):
            if not f.endswith(".txt"): continue
            p = os.path.join(d, f)
            for i, ln in enumerate(open(p), 1):
                ln = ln.strip()
                if not ln: continue
                parts = ln.split()
                if len(parts) != 5:
                    bad.append((p, i, "format", ln)); continue
                cid, *nums = parts
                if cid.isdigit() and int(cid) not in valid_ids:
                    bad.append((p, i, "class_out_of_range", ln))
                try:
                    x,y,w,h = map(float, nums)
                    if not (0 <= x <= 1 and 0 <= y <= 1 and 0 < w <= 1 and 0 < h <= 1):
                        bad.append((p, i, "coords_out_of_range", ln))
                except:
                    bad.append((p, i, "nan_value", ln))

print(f"Problems found: {len(bad)}")
for row in bad[:20]:
    print(row)

import os
base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample"
for d in ["Four Wheeler","Large Vehicle","Three Wheeler","Two Wheeler"]:
    for sp in ["train","valid","test"]:
        p = os.path.join(base, d, sp, "labels.cache")
        if os.path.exists(p):
            os.remove(p); print("🧹 removed", p)

import os

# ───────────────────────── Remap Three Wheeler: 0 → 2 ─────────────────────
print("═══ Fixing Three Wheeler class_id 0 → 2 ═══")
_tw_base = "c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Three Wheeler"
_tw_changed = 0
for sp in ["train", "valid", "test"]:
    _tw_d = os.path.join(_tw_base, sp, "labels")
    if not os.path.isdir(_tw_d): continue
    for f in os.listdir(_tw_d):
        if not f.endswith(".txt"): continue
        _p = os.path.join(_tw_d, f)
        with open(_p, "r") as fh:
            lines = [ln.strip() for ln in fh if ln.strip()]
        new_lines, touched = [], False
        for ln in lines:
            parts = ln.split()
            if parts and parts[0] == "0":
                parts[0] = "2"
                touched = True
            new_lines.append(" ".join(parts))
        if touched:
            with open(_p, "w") as fh:
                fh.write("\n".join(new_lines) + ("\n" if new_lines else ""))
            _tw_changed += 1
print(f"═══ Remapped annotations in {_tw_changed} Three Wheeler files ═══\n")

import os

# Where to save data.yaml
base_path = r"c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample"
out_path  = os.path.join(base_path, "data.yaml")

yaml_text = f"""# data.yaml (auto-generated)

path: "{base_path}"

train:
  - "{base_path}/Four Wheeler/train/images"
  - "{base_path}/Large Vehicle/train/images"
  - "{base_path}/Three Wheeler/train/images"
  - "{base_path}/Two Wheeler/train/images"

val:
  - "{base_path}/Four Wheeler/valid/images"
  - "{base_path}/Large Vehicle/valid/images"
  - "{base_path}/Three Wheeler/valid/images"
  - "{base_path}/Two Wheeler/valid/images"

test:
  - "{base_path}/Four Wheeler/test/images"
  - "{base_path}/Large Vehicle/test/images"
  - "{base_path}/Three Wheeler/test/images"
  - "{base_path}/Two Wheeler/test/images"

# number of classes
nc: 4

# class names (ids: 0–3)
names: ["Four_Wheeler", "Large_Vehicle", "Three_Wheeler", "Two_Wheeler"]
"""

os.makedirs(base_path, exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(yaml_text)

print(f"✅ Wrote YOLO config to: {out_path}")


# Check if the model has been downloaded (you should see 'yolov11s.pt' in your folder)
# !ls

# 6. Set the path to your data.yaml file (your dataset config file for YOLOv11)
yaml_file = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/data.yaml'

# 7. Train YOLOv11 on your custom dataset natively in Python
try:
    from ultralytics import YOLO
    import torch
    is_cpu = not torch.cuda.is_available()
    run_epochs = 5 if is_cpu else 50
    run_batch = 4 if is_cpu else 16
    print(f"🚀 Initializing YOLOv11s model training natively in Python... [{'CPU Optimized' if is_cpu else 'GPU Maximal'}]")
    yolo_model = YOLO('yolo11n.pt')
    yolo_model.train(data=yaml_file, epochs=run_epochs, batch=run_batch, imgsz=640, workers=0)
    weights = 'runs/detect/train/weights/best.pt'
except Exception as e:
    print(f"YOLO Training Exception: {e}")
    weights = 'yolov11s.pt'

# 8. Check training results
print(f"YOLO Training finished! Weights saved to runs/detect.")

from ultralytics import YOLO
import os, cv2
import matplotlib.pyplot as plt

# Paths
dataset_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

weights_loc = 'runs/detect/train/weights/best.pt'
weights = weights_loc if os.path.exists(weights_loc) else 'yolo11n.pt'

# Load model
model = YOLO(weights)

# Pick an image (fixing the casing & folders)
img_path = os.path.join(dataset_path, 'Four Wheeler', 'test', 'images', 'Four Wheeler_64.jpg')
if not os.path.exists(img_path):
    test_dir = os.path.join(dataset_path, 'Four Wheeler', 'test', 'images')
    candidates = [f for f in os.listdir(test_dir) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    img_path = os.path.join(test_dir, sorted(candidates)[0])

# Inference
results = model(img_path)  # or: model.predict(source=img_path, imgsz=640, conf=0.25)

# Visualize
res = results[0]
im_bgr = res.plot()  # annotated image (BGR)
plt.imshow(cv2.cvtColor(im_bgr, cv2.COLOR_BGR2RGB))
plt.axis('off'); plt.show()

# Extract boxes/classes/scores
boxes  = res.boxes.xyxy.cpu().numpy()
labels = res.boxes.cls.cpu().numpy().astype(int)
scores = res.boxes.conf.cpu().numpy()
names  = model.names

for (x1,y1,x2,y2), c, s in zip(boxes, labels, scores):
    print(f"{names[c]} {s:.2f} [{x1:.0f},{y1:.0f},{x2:.0f},{y2:.0f}]")

"""Faster R-CNN Implementation (PyTorch)"""

#pip Install

# GPU (CUDA 12.8) — recommended for RTX 3070/3060:
# pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

# CPU-only fallback (much slower training):
# pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

#1. Import necessary libraries:

import os
import torch
import xml.etree.ElementTree as ET
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
import torchvision.transforms.v2 as T
from tqdm import tqdm

import os

base = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

def walk_dirs(path, prefix=""):
    try:
        dirs = sorted(d for d in os.listdir(path) if os.path.isdir(os.path.join(path, d)))
    except FileNotFoundError:
        print("Path not found:", path); return
    for i, d in enumerate(dirs):
        last = (i == len(dirs) - 1)
        print(f"{prefix}{'└──' if last else '├──'} {d}")
        walk_dirs(os.path.join(path, d), prefix + ("    " if last else "│   "))

print(f"📂 {base}")
walk_dirs(base)

print(f"📂 {base}")
walk_dirs(base)

#code 1
import os
import torch
from PIL import Image
import xml.etree.ElementTree as ET
from torch.utils.data import Dataset

class VehicleDataset(Dataset):
    def __init__(self, image_dir, label_dir, transforms=None):
        """
        Args:
            image_dir (str): Directory containing images.
            label_dir (str): Directory containing annotations (XML files).
            transforms (callable, optional): Optional transform to be applied on a sample.
        """
        self.image_dir = image_dir
        self.label_dir = label_dir
        self.transforms = transforms

        # List all image files in the directory, sorted alphabetically
        self.image_files = sorted([f for f in os.listdir(self.image_dir) if f.endswith(('.png', '.jpg', '.jpeg'))])

    def __len__(self):
        """Return the total number of images."""
        return len(self.image_files)

    def __getitem__(self, idx):
        """
        Args:
            idx (int): Index of the sample to fetch.

        Returns:
            image (Tensor): The image data as a tensor.
            target (dict): The corresponding annotations (boxes, labels, etc.)
        """
        image_name = self.image_files[idx]
        image_path = os.path.join(self.image_dir, image_name)

        # Attempt to load the image, handle corrupted images
        try:
            image = Image.open(image_path).convert("RGB")
        except (OSError, IOError):
            print(f"Warning: Skipping invalid image {image_path}")
            return self.__getitem__((idx + 1) % len(self))  # Skip to the next valid image

        # Corresponding YOLO annotation file (.txt)
        annotation_name = os.path.splitext(image_name)[0] + '.txt'
        annotation_path = os.path.join(self.label_dir, annotation_name)

        # Lists for bounding boxes and labels
        boxes = []
        labels = []

        # Read YOLO-format annotations: class_id x_center y_center width height (normalized)
        if os.path.exists(annotation_path):
            img_w, img_h = image.size  # Get image dimensions for denormalization
            with open(annotation_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    parts = line.split()
                    if len(parts) != 5:
                        continue
                    class_id = int(parts[0])
                    x_center, y_center, w, h = map(float, parts[1:])
                    # Convert YOLO normalized coords to absolute pixel coords
                    xmin = (x_center - w / 2) * img_w
                    ymin = (y_center - h / 2) * img_h
                    xmax = (x_center + w / 2) * img_w
                    ymax = (y_center + h / 2) * img_h
                    boxes.append([round(xmin), round(ymin), round(xmax), round(ymax)])
                    # Faster R-CNN uses 0 for background, so shift class_id by +1
                    labels.append(class_id + 1)

        # Ensure boxes is a tensor, even if it's empty
        boxes = torch.as_tensor(boxes, dtype=torch.float32) if boxes else torch.zeros((0, 4), dtype=torch.float32)
        labels = torch.as_tensor(labels, dtype=torch.int64)

        # Image ID, area (for each bounding box), and crowd info (for segmentation tasks)
        image_id = torch.tensor([idx])
        area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0])  # Area = (width * height) for each box
        iscrowd = torch.zeros((boxes.shape[0],), dtype=torch.int64)  # Not for segmentation

        # Organize target information
        target = {
            "boxes": boxes,
            "labels": labels,
            "image_id": image_id,
            "area": area,
            "iscrowd": iscrowd
        }

        # Apply transformations if any (only to the image, not to the annotations)
        if self.transforms:
            image = self.transforms(image)

        return image, target

#code 2
import torchvision.transforms as T
import os
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
from torch.utils.data import ConcatDataset

# Define the transformation function for training and validation
def get_transform(train):
    """
    Define the transformations for the images.

    Args:
        train (bool): Whether the transformation is for training or not.

    Returns:
        Compose: A composed transformation for the image.
    """
    transforms = []
    transforms.append(T.ToTensor())  # Convert image to Tensor

    if train:
        transforms.append(T.RandomHorizontalFlip(0.5))  # Random horizontal flip during training

    # Return a composed transform that handles both image and target
    return T.Compose(transforms)

# Base path
base_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample'

# Define a list of vehicle types
vehicle_types = ['Four Wheeler', 'Large Vehicle', 'Three Wheeler', 'Two Wheeler']

# Initialize lists to hold datasets for all vehicle types
datasets_train = []
datasets_valid = []

# Iterate over each vehicle type
for vehicle_type in vehicle_types:
    # Construct the train and valid directories for the current vehicle type
    train_image_dir = os.path.join(base_path, vehicle_type, 'train', 'images')
    valid_image_dir = os.path.join(base_path, vehicle_type, 'valid', 'images')

    train_label_dir = os.path.join(base_path, vehicle_type, 'train', 'labels')
    valid_label_dir = os.path.join(base_path, vehicle_type, 'valid', 'labels')

    # Print the paths (optional for debugging)
    print(f"Loading training data from: {os.path.abspath(train_image_dir)}")
    print(f"Loading validation data from: {os.path.abspath(valid_image_dir)}")

    # Use the VehicleDataset class to load datasets for the current vehicle type
    dataset_train = VehicleDataset(image_dir=train_image_dir, label_dir=train_label_dir, transforms=get_transform(train=True))
    dataset_valid = VehicleDataset(image_dir=valid_image_dir, label_dir=valid_label_dir, transforms=get_transform(train=False))

    # Append datasets for each vehicle type to the lists
    datasets_train.append(dataset_train)
    datasets_valid.append(dataset_valid)

# Combine all datasets (for example, use concatenation)
full_dataset_train = ConcatDataset(datasets_train)
full_dataset_valid = ConcatDataset(datasets_valid)

# Collate function to handle batching
def collate_fn(batch):
    """
    Collate function to handle batching of image and target.

    Args:
        batch (list): A list of tuples containing (image, target) for each sample.

    Returns:
        tuple: A tuple of images and targets for the batch.
    """
    return tuple(zip(*batch))

# DataLoaders (num_workers=0 is required for Windows)
data_loader_train = DataLoader(
    full_dataset_train, batch_size=2, shuffle=True, num_workers=0,
    collate_fn=collate_fn
)

data_loader_valid = DataLoader(
    full_dataset_valid, batch_size=1, shuffle=False, num_workers=0,
    collate_fn=collate_fn
)

#code 3
import torch
import torchvision
from torch.utils.data import DataLoader
from tqdm import tqdm

# Check if GPU is available, otherwise fallback to CPU
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print(f"Using device: {device}")

# Our dataset has 2 classes: 1 (car) + 0 (background)
num_classes = 5  # 4 vehicle classes + 1 background

# Load a pre-trained Faster R-CNN model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights='DEFAULT')

# Get the number of input features for the classifier
in_features = model.roi_heads.box_predictor.cls_score.in_features

# Replace the pre-trained head with a new one for our number of classes
model.roi_heads.box_predictor = torchvision.models.detection.faster_rcnn.FastRCNNPredictor(in_features, num_classes)

# Move model to the appropriate device
model.to(device)

# Use DataParallel if multiple GPUs are available
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)
    print(f"Using {torch.cuda.device_count()} GPUs!")

# --- Training Setup ---
# Define optimizer and learning rate scheduler
params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.SGD(params, lr=0.005, momentum=0.9, weight_decay=0.0005)
lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.1)

num_epochs = 3 if not torch.cuda.is_available() else 10
print(f"--- Faster R-CNN Training Configuration: {num_epochs} Epochs ---")

# --- Training Loop ---
for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    print(f"--- Epoch {epoch+1}/{num_epochs} ---")

    epoch_loss = 0
    for images, targets in tqdm(data_loader_train, desc=f"Training Epoch {epoch+1}"):
        # Move images and targets to the appropriate device (GPU or CPU)
        images = list(image.to(device) for image in images)
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        # Forward pass
        loss_dict = model(images, targets)

        # Total loss
        losses = sum(loss for loss in loss_dict.values())
        loss_value = losses.item()
        epoch_loss += loss_value

        # Backward pass and optimization
        optimizer.zero_grad()
        losses.backward()
        optimizer.step()

    # Step the learning rate scheduler
    lr_scheduler.step()

    # Print loss for the current epoch
    print(f"---- Epoch {epoch+1} finished. Average loss: {epoch_loss/len(data_loader_train):.4f} ----")

print("--- Training complete. ---")

# Save the trained model
torch.save(model.state_dict(), 'fasterrcnn_car_detector.pth')
print("Model saved to fasterrcnn_car_detector.pth")

#Inference

import os

# Save the model directly to the project directory
model_path = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/fasterrcnn_car_detector.pth'
torch.save(model.state_dict(), model_path)
print(f"Model saved locally to {model_path}")

import torch
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from PIL import Image
import torchvision.transforms as T
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# 1. Load the trained model from the local environment
model = fasterrcnn_resnet50_fpn(pretrained=False)
in_features = model.roi_heads.box_predictor.cls_score.in_features
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, 5) # 5 classes: 4 vehicles + background
model.load_state_dict(torch.load(model_path, map_location=device))
model.eval()
model.to(device)

#visualize the detection results

# 2. Load and preprocess the image
_test_dir = r'c:/Users/OMEN/Documents/Engr Abubakar Isa Project/sample/Large Vehicle/test/images'
_candidates = sorted([f for f in os.listdir(_test_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
image_path = os.path.join(_test_dir, _candidates[0])
print(f"Running Faster R-CNN inference on: {image_path}")
image = Image.open(image_path).convert('RGB')
transform = T.ToTensor()
img_tensor = transform(image).unsqueeze(0).to(device)  # Add batch dimension

# 3. Run inference
with torch.no_grad():
    outputs = model(img_tensor)

# 4. Visualize the image and the detected bounding boxes
fig, ax = plt.subplots(1)
ax.imshow(image)

# The 'outputs' will contain boxes, labels, and scores
boxes = outputs[0]['boxes'].cpu()
scores = outputs[0]['scores'].cpu()
labels = outputs[0]['labels'].cpu()
threshold = 0.5  # Only consider detections above 50% confidence

class_mapping = {1: 'Four_Wheeler', 2: 'Large_Vehicle', 3: 'Three_Wheeler', 4: 'Two_Wheeler'}

# Draw bounding boxes and display labels for high-confidence detections
for i, box in enumerate(boxes):
    if scores[i] >= threshold:
        x1, y1, x2, y2 = box.cpu().numpy()
        class_id = int(labels[i])
        class_name = class_mapping.get(class_id, f"Unknown ({class_id})")
        rect = patches.Rectangle((x1, y1), x2 - x1, y2 - y1,
                                 linewidth=2, edgecolor='r', facecolor='none')
        ax.add_patch(rect)
        ax.text(x1, y1, f"{class_name} {scores[i]:.2f}", color='yellow', fontsize=8, backgroundcolor='black')

plt.axis('off')
plt.title(f"Fast R-CNN Detections > {threshold*100}% CF")
plt.show()

# 5. Print results (box coordinates, labels, and scores)
print(f"Detected boxes: {boxes}")
print(f"Detected scores: {scores}")
